// Generated by services/api/scripts/generate_job_contracts.py. Do not edit.
export type AgentMemory = {
  scope: string;
  summary: string;
};

export type ArtifactUnit = {
  unit_index: number;
  title: string;
  body: string;
  evidence: Array<string>;
  missing_facts: Array<string>;
  layout?: "cover" | "text" | "image" | "table";
  image_id?: string | null;
  table?: Array<Array<string>>;
};

export type ClaimedJob = {
  job: GenerationJobDetail;
  lease_id: string;
  skills: Array<SkillSnapshot>;
  current_units: Array<ArtifactUnit>;
  sources?: Array<Record<string, unknown>>;
  revision_units?: Array<number>;
  memory?: AgentMemory | null;
};

export type DocumentPlan = {
  skill_slug: string;
  summary: string;
  sections: Array<PlanSection>;
};

export type GenerationBatchRecord = {
  batch_index: number;
  start_unit: number;
  end_unit: number;
  status: "pending" | "draft" | "completed";
  draft_count: number;
  review?: ReviewResult | null;
};

export type GenerationJobCreate = {
  project_id: string;
  conversation_id?: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size?: number;
  max_revision_rounds?: number;
  max_model_calls?: number;
  max_total_tokens?: number;
};

export type GenerationJobDetail = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size: number;
  max_revision_rounds: number;
  status: "queued" | "running" | "waiting_outline" | "waiting_storyboard" | "needs_review" | "completed" | "failed" | "cancelled";
  stage: "planning" | "storyboarding" | "generating" | "final_review";
  completed_units: number;
  storyboard_units: number;
  model_calls: number;
  total_tokens: number;
  max_model_calls: number;
  max_total_tokens: number;
  model: string;
  review_model: string;
  error?: string | null;
  failure_kind?: "budget" | "context" | "configuration" | "provider" | "workflow" | null;
  created_at: string;
  updated_at: string;
  outline?: DocumentPlan | null;
  batches: Array<GenerationBatchRecord>;
  final_review?: ReviewResult | null;
  progress?: string | null;
};

export type GenerationJobEvent = {
  id: number;
  job_id: string;
  event_type: string;
  message: string;
  created_at: string;
};

export type GenerationJobRecord = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size: number;
  max_revision_rounds: number;
  status: "queued" | "running" | "waiting_outline" | "waiting_storyboard" | "needs_review" | "completed" | "failed" | "cancelled";
  stage: "planning" | "storyboarding" | "generating" | "final_review";
  completed_units: number;
  storyboard_units: number;
  model_calls: number;
  total_tokens: number;
  max_model_calls: number;
  max_total_tokens: number;
  model: string;
  review_model: string;
  error?: string | null;
  failure_kind?: "budget" | "context" | "configuration" | "provider" | "workflow" | null;
  created_at: string;
  updated_at: string;
};

export type JobCheckpoint = {
  action: "plan" | "storyboard" | "draft" | "review" | "final_review" | "failure";
  plan?: DocumentPlan | null;
  batch?: UnitBatch | null;
  review?: ReviewResult | null;
  error?: string | null;
  failure_kind?: "budget" | "context" | "configuration" | "provider" | "workflow" | null;
};

export type PlanSection = {
  title: string;
  start_unit: number;
  end_unit: number;
  objective: string;
};

export type ReviewResult = {
  passed: boolean;
  summary: string;
  issues: Array<string>;
};

export type SkillSnapshot = {
  slug: string;
  description: string;
  sha256: string;
  files: Record<string, string>;
};

export type UnitBatch = {
  units: Array<ArtifactUnit>;
};

export type UsageRecord = {
  call_id: string;
  model: string;
  total_tokens: number;
};

export type WorkerProgress = {
  step: "skills" | "materials" | "planning" | "storyboarding" | "generating" | "reviewing" | "compacting" | "continuing";
  memory?: AgentMemory | null;
};

export const schemas = {"DocumentPlan": {"properties": {"skill_slug": {"maxLength": 100, "minLength": 1, "type": "string"}, "summary": {"maxLength": 4000, "minLength": 1, "type": "string"}, "sections": {"items": {"properties": {"title": {"maxLength": 200, "minLength": 1, "type": "string"}, "start_unit": {"maximum": 500, "minimum": 1, "type": "integer"}, "end_unit": {"maximum": 500, "minimum": 1, "type": "integer"}, "objective": {"maxLength": 2000, "minLength": 1, "type": "string"}}, "required": ["title", "start_unit", "end_unit", "objective"], "type": "object"}, "maxItems": 30, "minItems": 1, "type": "array"}}, "required": ["skill_slug", "summary", "sections"], "type": "object"}, "UnitBatch": {"properties": {"units": {"items": {"properties": {"unit_index": {"maximum": 500, "minimum": 1, "type": "integer"}, "title": {"maxLength": 200, "minLength": 1, "type": "string"}, "body": {"maxLength": 12000, "minLength": 1, "type": "string"}, "evidence": {"items": {"type": "string"}, "maxItems": 30, "type": "array"}, "missing_facts": {"items": {"type": "string"}, "maxItems": 30, "type": "array"}, "layout": {"default": "text", "enum": ["cover", "text", "image", "table"], "type": "string"}, "image_id": {"anyOf": [{"type": "string"}, {"type": "null"}], "default": null}, "table": {"items": {"items": {"type": "string"}, "type": "array"}, "maxItems": 15, "type": "array"}}, "required": ["unit_index", "title", "body", "evidence", "missing_facts"], "type": "object"}, "maxItems": 10, "minItems": 1, "type": "array"}}, "required": ["units"], "type": "object"}, "ReviewResult": {"properties": {"passed": {"type": "boolean"}, "summary": {"maxLength": 4000, "minLength": 1, "type": "string"}, "issues": {"items": {"type": "string"}, "maxItems": 30, "type": "array"}}, "required": ["passed", "summary", "issues"], "type": "object"}};
