services:
  nginx:
    ports:
      - ${BIND_ADDRESS:-0.0.0.0}:${HTTPS_PORT:-443}:443
    volumes:
      - ./deploy/nginx/https.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ${LETSENCRYPT_CONFIG_DIR:-./.local/certbot/config}:/etc/letsencrypt:ro
