// Generated by services/api/scripts/generate_job_contracts.py. Do not edit.
export type ArtifactUnit = {
  unit_index: number;
  title: string;
  body: string;
  evidence: Array<string>;
  missing_facts: Array<string>;
};

export type ClaimedJob = {
  job: GenerationJobDetail;
  lease_id: string;
  skills: Array<SkillSnapshot>;
  current_units: Array<ArtifactUnit>;
};

export type DocumentPlan = {
  skill_slug: string;
  summary: string;
  sections: Array<PlanSection>;
};

export type GenerationBatchRecord = {
  batch_index: number;
  start_unit: number;
  end_unit: number;
  status: "pending" | "draft" | "completed";
  draft_count: number;
  review?: ReviewResult | null;
};

export type GenerationJobCreate = {
  project_id: string;
  conversation_id?: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size?: number;
  max_revision_rounds?: number;
  max_model_calls?: number;
  max_total_tokens?: number;
};

export type GenerationJobDetail = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size: number;
  max_revision_rounds: number;
  status: "queued" | "running" | "waiting_outline" | "waiting_storyboard" | "needs_review" | "completed" | "failed" | "cancelled";
  stage: "planning" | "storyboarding" | "generating" | "final_review";
  completed_units: number;
  storyboard_units: number;
  model_calls: number;
  total_tokens: number;
  max_model_calls: number;
  max_total_tokens: number;
  model: string;
  review_model: string;
  error?: string | null;
  created_at: string;
  updated_at: string;
  outline?: DocumentPlan | null;
  batches: Array<GenerationBatchRecord>;
  final_review?: ReviewResult | null;
};

export type GenerationJobEvent = {
  id: number;
  job_id: string;
  event_type: string;
  message: string;
  created_at: string;
};

export type GenerationJobRecord = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size: number;
  max_revision_rounds: number;
  status: "queued" | "running" | "waiting_outline" | "waiting_storyboard" | "needs_review" | "completed" | "failed" | "cancelled";
  stage: "planning" | "storyboarding" | "generating" | "final_review";
  completed_units: number;
  storyboard_units: number;
  model_calls: number;
  total_tokens: number;
  max_model_calls: number;
  max_total_tokens: number;
  model: string;
  review_model: string;
  error?: string | null;
  created_at: string;
  updated_at: string;
};

export type JobCheckpoint = {
  action: "plan" | "storyboard" | "draft" | "review" | "final_review" | "failure";
  plan?: DocumentPlan | null;
  batch?: UnitBatch | null;
  review?: ReviewResult | null;
  error?: string | null;
};

export type PlanSection = {
  title: string;
  start_unit: number;
  end_unit: number;
  objective: string;
};

export type ReviewResult = {
  passed: boolean;
  summary: string;
  issues: Array<string>;
};

export type SkillSnapshot = {
  slug: string;
  description: string;
  sha256: string;
  files: Record<string, string>;
};

export type UnitBatch = {
  units: Array<ArtifactUnit>;
};

export type UsageRecord = {
  call_id: string;
  model: string;
  total_tokens: number;
};
