// Generated by services/api/scripts/generate_job_contracts.py. Do not edit.
export type ArtifactKind = "outline" | "storyboard" | "draft";
export type AgentMemory = {
  scope: string;
  summary: string;
};

export type ArtifactUnit = {
  unit_index: number;
  title: string;
  body: string;
  evidence: Array<string>;
  missing_facts: Array<string>;
  layout?: "cover" | "text" | "image" | "table";
  image_id?: string | null;
  table?: Array<Array<string>>;
};

export type ClaimedJob = {
  job: GenerationJobDetail;
  lease_id: string;
  skills: Array<SkillSnapshot>;
  current_units: Array<ArtifactUnit>;
  sources?: Array<Record<string, unknown>>;
  revision_units?: Array<number>;
  memory?: AgentMemory | null;
};

export type CommentAnchor = {
  unit_index: number;
  quote: string;
};

export type DocumentPlan = {
  skill_slug: string;
  summary: string;
  sections: Array<PlanSection>;
  target_units: number;
};

export type GenerationBatchRecord = {
  batch_index: number;
  start_unit: number;
  end_unit: number;
  status: "pending" | "draft" | "completed";
  draft_count: number;
  review?: ReviewResult | null;
};

export type GenerationJobCreate = {
  project_id: string;
  conversation_id?: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  batch_size?: number;
  max_revision_rounds?: number;
  count_override?: boolean;
  max_model_calls?: number | null;
  max_total_tokens?: number | null;
};

export type GenerationJobDetail = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  count_override?: boolean;
  scope_mismatch?: boolean;
  parent_id?: string | null;
  feedback_kind?: "outline" | "storyboard" | "draft" | null;
  batch_size: number;
  max_revision_rounds: number;
  status: "queued" | "running" | "waiting_outline" | "waiting_storyboard" | "waiting_review" | "needs_review" | "completed" | "failed" | "cancelled";
  stage: "planning" | "storyboarding" | "generating" | "final_review";
  completed_units: number;
  storyboard_units: number;
  model_calls: number;
  total_tokens: number;
  max_model_calls: number;
  max_total_tokens: number;
  model: string;
  review_model: string;
  error?: string | null;
  failure_kind?: "budget" | "context" | "configuration" | "provider" | "workflow" | null;
  created_at: string;
  updated_at: string;
  storyboard_range?: Array<number> | null;
  outline?: DocumentPlan | null;
  batches: Array<GenerationBatchRecord>;
  final_review?: ReviewResult | null;
  progress?: string | null;
  review_request?: ReviewSnapshot | null;
};

export type GenerationJobEvent = {
  id: number;
  job_id: string;
  event_type: string;
  message: string;
  created_at: string;
};

export type GenerationJobRecord = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  module: "concept" | "bid" | "drawing";
  goal: string;
  target_units: number;
  count_override?: boolean;
  scope_mismatch?: boolean;
  parent_id?: string | null;
  feedback_kind?: "outline" | "storyboard" | "draft" | null;
  batch_size: number;
  max_revision_rounds: number;
  status: "queued" | "running" | "waiting_outline" | "waiting_storyboard" | "waiting_review" | "needs_review" | "completed" | "failed" | "cancelled";
  stage: "planning" | "storyboarding" | "generating" | "final_review";
  completed_units: number;
  storyboard_units: number;
  model_calls: number;
  total_tokens: number;
  max_model_calls: number;
  max_total_tokens: number;
  model: string;
  review_model: string;
  error?: string | null;
  failure_kind?: "budget" | "context" | "configuration" | "provider" | "workflow" | null;
  created_at: string;
  updated_at: string;
};

export type JobCheckpoint = {
  action: "plan" | "storyboard" | "draft" | "review" | "final_review" | "failure";
  plan?: DocumentPlan | null;
  batch?: UnitBatch | null;
  review?: ReviewResult | null;
  error?: string | null;
  failure_kind?: "budget" | "context" | "configuration" | "provider" | "workflow" | null;
};

export type PlanSection = {
  title: string;
  start_unit: number;
  end_unit: number;
  objective: string;
};

export type RequirementDraft = {
  module: "concept" | "bid" | "drawing";
  goal: string;
  base_goal?: string;
  fallback_units?: number;
};

export type ResolvedRequirement = {
  target_units: number;
  requested_units: number | null;
  count_override: boolean;
};

export type ReviewComment = {
  kind: "outline" | "storyboard" | "draft";
  body: string;
  anchor?: CommentAnchor | null;
  id: string;
  job_id: string;
  snapshot_hash?: string | null;
  created_at: string;
  submitted_job_id?: string | null;
};

export type ReviewCommentCreate = {
  kind: "outline" | "storyboard" | "draft";
  body: string;
  anchor?: CommentAnchor | null;
};

export type ReviewResult = {
  passed: boolean;
  summary: string;
  issues: Array<string>;
};

export type ReviewSnapshot = {
  parent_id: string;
  kind: "outline" | "storyboard" | "draft";
  comments: Array<ReviewComment>;
  original_outline?: DocumentPlan | null;
};

export type ReviewSubmission = {
  kind: "outline" | "storyboard" | "draft";
  overall?: string;
  comment_ids?: Array<string>;
};

export type RunLimits = {
  max_model_calls: number;
  max_total_tokens: number;
};

export type SkillSnapshot = {
  slug: string;
  description: string;
  sha256: string;
  files: Record<string, string>;
};

export type UnitBatch = {
  units: Array<ArtifactUnit>;
};

export type UsageRecord = {
  call_id: string;
  model: string;
  total_tokens: number;
};

export type WorkerProgress = {
  step: "skills" | "materials" | "planning" | "storyboarding" | "generating" | "reviewing" | "compacting" | "continuing";
  memory?: AgentMemory | null;
};

export const runLimitsSchema = {"properties": {"max_model_calls": {"maximum": 100000, "minimum": 1, "title": "Max Model Calls", "type": "integer"}, "max_total_tokens": {"maximum": 1000000000, "minimum": 1000, "title": "Max Total Tokens", "type": "integer"}}, "required": ["max_model_calls", "max_total_tokens"], "title": "RunLimits", "type": "object"} as const;
