"""Generate shared wire types/tool schemas from Pydantic, not a second hand-written contract."""
import json
from pathlib import Path
from pydantic import TypeAdapter

from archflow_api import models


def typescript(schema: dict) -> str:
    if isinstance(schema, bool):
        return "unknown" if schema else "never"
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(typescript(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        if "properties" not in schema:
            return f"Record<string, {typescript(schema.get('additionalProperties', {}))}>"
        required = schema.get("required", [])
        return "{\n" + "\n".join(
            f"  {name}{'' if name in required else '?'}: {typescript(value)};"
            for name, value in schema["properties"].items()
        ) + "\n}"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def resolve(schema: dict, definitions: dict) -> dict:
    if not isinstance(schema, dict):
        return schema
    if "$ref" in schema:
        return resolve(definitions[schema["$ref"].split("/")[-1]], definitions)
    return {key: ({name: resolve(field, definitions) for name, field in value.items()} if key == "properties"
                  else [resolve(v, definitions) for v in value] if isinstance(value, list)
                  else resolve(value, definitions) if isinstance(value, dict) else value)
            for key, value in schema.items() if key not in {"$defs", "title"}}


root = Path(__file__).resolve().parents[3]
definitions = {}
names = ["GenerationJobCreate", "GenerationJobRecord", "GenerationJobDetail", "ClaimedJob", "JobCheckpoint", "UsageRecord", "GenerationJobEvent", "WorkerProgress", "WorkerDiagnostic", "RunLimits", "RequirementDraft", "ResolvedRequirement", "ReviewCommentCreate", "ReviewComment", "ReviewSubmission"]
for name in names:
    schema = getattr(models, name).model_json_schema()
    definitions.update(schema.pop("$defs", {}))
    definitions[name] = schema
types = "// Generated by services/api/scripts/generate_job_contracts.py. Do not edit.\n"
types += f"export type ArtifactKind = {typescript(TypeAdapter(models.ArtifactKind).json_schema())};\n"
types += "\n".join(f"export type {name} = {typescript(schema)};\n" for name, schema in sorted(definitions.items()))
schemas = {name: resolve(definitions[name], definitions) for name in ["DocumentPlan", "UnitBatch", "ReviewResult"]}
for target in ["services/agent/src/contracts.ts", "apps/web/lib/job-contracts.ts"]:
    path = root / target
    path.parent.mkdir(parents=True, exist_ok=True)
    constants = "\nexport const schemas = " + json.dumps(schemas, ensure_ascii=False) + ";\n" if "agent" in target else "\nexport const runLimitsSchema = " + json.dumps(definitions["RunLimits"], ensure_ascii=False) + " as const;\n"
    path.write_text(types + constants)
